fail_fast : true

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: ''
        hooks:
        -   id: check-ast
        -   id: check-executables-have-shebangs
            exclude: "__init__.py"
        -   id: check-symlinks
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: flake8
            args: [--max-line-length=90, --ignore=F401]

    -   repo: https://github.com/jumanjihouse/pre-commit-hooks
        rev: ''
        hooks:
        -   id: shellcheck

    -   repo: https://github.com/psf/black
        rev: ''
        hooks:
        -   id: black
            language_version: python3.6
